/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import backend.IRecordsStorage;
import javax.swing.JOptionPane;

/**
 *
 * @author FOyeyipo
 */
public class DisplayPanel extends javax.swing.JFrame {

    
        IRecordsStorage iRecordsStorage;
    /**
     * Creates new form DisplayPanel
     * @param iRecodsStorage
     */
    public DisplayPanel(IRecordsStorage iRecodsStorage) {
        this.iRecordsStorage = iRecordsStorage;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        textile = new javax.swing.JRadioButton();
        other = new javax.swing.JRadioButton();
        all = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        reviewArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("DisplayPanel");
        setAlwaysOnTop(true);

        buttonGroup1.add(textile);
        textile.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textile.setText("Textile");
        textile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textile.setBorderPainted(true);
        textile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textileActionPerformed(evt);
            }
        });

        buttonGroup1.add(other);
        other.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        other.setText("Other");
        other.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        other.setBorderPainted(true);
        other.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherActionPerformed(evt);
            }
        });

        buttonGroup1.add(all);
        all.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        all.setText("All");
        all.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        all.setBorderPainted(true);
        all.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allActionPerformed(evt);
            }
        });

        reviewArea.setColumns(20);
        reviewArea.setRows(5);
        jScrollPane1.setViewportView(reviewArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(other, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textile, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(all, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(textile)
                .addGap(41, 41, 41)
                .addComponent(other)
                .addGap(50, 50, 50)
                .addComponent(all)
                .addContainerGap(126, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textileActionPerformed
        // TODO add your handling code here:
        textile.setSelected(true);
//       String storageInteface = iRecordsStorage.retrieveRecordToDisplay(RecordType.TEXTILE);
//       
//        String display = reviewArea.getText();
////        reviewAreaAncestorAdded(storageInteface);
        
        JOptionPane.showMessageDialog(textile, "You have selected Textile");
    
                
    }//GEN-LAST:event_textileActionPerformed

    private void otherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherActionPerformed
         other.setSelected(true);
         
        
        JOptionPane.showMessageDialog(other, "You have selected Other");
    
    }//GEN-LAST:event_otherActionPerformed

    private void allActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allActionPerformed
         all.setSelected(true);
        
      
        JOptionPane.showMessageDialog(all, "Are you Sure you want ALL");
    
    }//GEN-LAST:event_allActionPerformed

    
    public void viewArea(){
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DisplayPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DisplayPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DisplayPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DisplayPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         IRecordsStorage iRecordsStorage;

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
//            new DisplayPanel(iRecordsStorage).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton all;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton other;
    private javax.swing.JTextArea reviewArea;
    private javax.swing.JRadioButton textile;
    // End of variables declaration//GEN-END:variables
}
